version: "3.7"

networks:
  sustainability:
    driver: bridge

services:
  #PHP FPM
  php:
    container_name: "php_sustainability"
    build:
      args:
        user: sustainability
        uid: 1588
      context: ./docker/php
    image: php:8.0-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sustainability

 #Nginx Service
  nginx:
    container_name: "nginx_sustainability"
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "9101:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sustainability
  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "9102:80"
    depends_on:
      - "mysql"
    networks:
      - sustainability
  mysql:
    container_name: "sustainability_mysql_database"
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docke/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3312:3306"
    networks:
      - sustainability
